-- Generated by Fix-POSImages.ps1 on 06/29/2026 14:23:52
-- Run in phpMyAdmin: gym_db > SQL tab

-- 1. Fix column default
ALTER TABLE `pos_items` MODIFY COLUMN `image` VARCHAR(255) NULL DEFAULT NULL;
UPDATE `pos_items` SET `image` = NULL WHERE `image` = '0' OR `image` = '';

-- 2. Link existing uploaded images to products
UPDATE `pos_items` SET `image` = 'uploads/products/product_1_1782711063.jpeg' WHERE id = 1 AND (image IS NULL OR image = '' OR image = '0');
UPDATE `pos_items` SET `image` = 'uploads/products/product_2_1782714202.jpg' WHERE id = 2 AND (image IS NULL OR image = '' OR image = '0');
UPDATE `pos_items` SET `image` = 'uploads/products/product_3_1782714187.jpg' WHERE id = 3 AND (image IS NULL OR image = '' OR image = '0');
UPDATE `pos_items` SET `image` = 'uploads/products/product_5_1782713803.jpg' WHERE id = 5 AND (image IS NULL OR image = '' OR image = '0');
UPDATE `pos_items` SET `image` = 'uploads/products/product_6_1782711093.jpg' WHERE id = 6 AND (image IS NULL OR image = '' OR image = '0');
UPDATE `pos_items` SET `image` = 'uploads/products/product_9_1782711148.jpeg' WHERE id = 9 AND (image IS NULL OR image = '' OR image = '0');
UPDATE `pos_items` SET `image` = 'uploads/products/product_10_1782711134.jpeg' WHERE id = 10 AND (image IS NULL OR image = '' OR image = '0');

-- 3. Verify
SELECT id, name, image FROM `pos_items` WHERE image IS NOT NULL ORDER BY id;
